export const demoThemeJimpower = () => ({
  "text-primary-color": "var(--primary-text-color)",
  "paper-item-icon-color": "var(--primary-text-color)",
  "primary-color": "#5294E2",
  "label-badge-red": "var(--accent-color)",
  "paper-tabs-selection-bar-color": "green",
  "paper-slider-knob-color": "var(--accent-color)",
  "light-primary-color": "var(--accent-color)",
  "primary-background-color": "#383C45",
  "primary-text-color": "#FFFFFF",
  "paper-item-selected_-_background-color": "#434954",
  "paper-slider-active-color": "var(--accent-color)",
  "secondary-background-color": "#383C45",
  "paper-slider-container-color":
    "linear-gradient(var(--primary-background-color), var(--secondary-background-color)) no-repeat",
  "paper-slider-disabled-active-color": "var(--disabled-text-color)",
  "disabled-text-color": "#7F848E",
  "paper-item-icon_-_color": "green",
  "paper-grey-200": "#414A59",
  "label-badge-background-color": "#2E333A",
  "paper-card-header-color": "var(--accent-color)",
  "sidebar-icon-color": "var(--paper-item-icon-color)",
  "paper-listbox-background-color": "#2E333A",
  "table-row-background-color": "#353840",
  "paper-grey-50": "var(--primary-text-color)",
  "switch-checked-color": "var(--accent-color)",
  "paper-dialog-background-color": "#434954",
  "secondary-text-color": "#5294E2",
  "google-red-500": "#E45E65",
  "divider-color": "rgba(0, 0, 0, .12)",
  "google-green-500": "#39E949",
  "switch-unchecked-button-color": "var(--disabled-text-color)",
  "label-badge-border-color": "green",
  "paper-listbox-color": "var(--primary-color)",
  "paper-slider-disabled-secondary-color": "var(--disabled-text-color)",
  "paper-card-background-color": "#434954",
  "label-badge-text-color": "var(--primary-text-color)",
  "paper-slider-knob-start-color": "var(--accent-color)",
  "switch-unchecked-track-color": "var(--disabled-text-color)",
  "dark-primary-color": "var(--accent-color)",
  "paper-slider-secondary-color": "var(--secondary-background-color)",
  "paper-slider-pin-color": "var(--accent-color)",
  "paper-item-icon-active-color": "#F9C536",
  "accent-color": "#E45E65",
  "table-row-alternative-background-color": "#3E424B",
});
