version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
      time: "06:00"
    cooldown:
      default-days-before-reopen: 30
      default-days: 7
    open-pull-requests-limit: 10
    labels:
      - Dependencies
      - GitHub Actions
