approvedGitRepositories:
  - "**"

compressionLevel: mixed

defaultSemverRangePrefix: ""

enableGlobalCache: false

enableScripts: true

nodeLinker: node-modules

npmMinimalAgeGate: 3d

yarnPath: .yarn/releases/yarn-4.15.0.cjs
