# https://dev.azure.com/home-assistant

trigger:
  batch: true
  branches:
    include:
    - dev
  paths:
    include:
    - translations/en.json
pr: none
schedules:
  - cron: "30 0 * * *"
    displayName: "frontend translation update"
    branches:
      include:
      - dev
    always: true
variables:
- group: translation
resources:
  repositories:
  - repository: azure
    type: github
    name: 'home-assistant/ci-azure'
    endpoint: 'home-assistant'


jobs:

- job: 'Upload'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: NodeTool@0
    displayName: 'Use Node 12.x'
    inputs:
      versionSpec: '12.x'
  - script: |
      export LOKALISE_TOKEN="$(lokaliseToken)"
      export AZURE_BRANCH="$(Build.SourceBranchName)"

      ./script/translations_upload_base
    displayName: 'Upload Translation'

- job: 'Download'
  dependsOn:
  - 'Upload'
  condition: or(eq(variables['Build.Reason'], 'Schedule'), eq(variables['Build.Reason'], 'Manual'))
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: NodeTool@0
    displayName: 'Use Node 12.x'
    inputs:
      versionSpec: '12.x'
  - template: templates/azp-step-git-init.yaml@azure
  - script: |
      export LOKALISE_TOKEN="$(lokaliseToken)"
      export AZURE_BRANCH="$(Build.SourceBranchName)"

      npm install
      ./script/translations_download
    displayName: 'Download Translation'
  - script: |
      git checkout dev
      git add translation
      git commit -am "[ci skip] Translation update"
      git push
    displayName: 'Update translation'
