#!/bin/bash


jsfiles=$(git diff --name-only dev HEAD | grep ".js")
tsfiles=$(git diff --name-only dev HEAD | grep ".ts")

echo $jsfiles
[[ -z $jsfiles ]] || node_modules/.bin/eslint $(echo $jsfiles)
echo $tsfiles
[[ -z $tsfiles ]] || node_modules/.bin/tslint $(echo $tsfiles)

node_modules/.bin/tsc

# node_modules/.bin/tsc --jsx react --jsxFactory h --target es2017 --module esnext --moduleResolution node --lib es2017,dom,dom.iterable --noEmit --noUnusedLocals --noUnusedParameters --noImplicitReturns --noFallthroughCasesInSwitch --strict --noImplicitAny false --skipLibCheck --resolveJsonModule --experimentalDecorators $(echo $tsfiles)
