export const demoThemeTeachingbirds = () => ({
  "paper-card-header-color": "var(--paper-item-icon-color)",
  "paper-listbox-background-color": "#202020",
  "paper-grey-50": "var(--primary-text-color)",
  "paper-item-icon-color": "#d3d3d3",
  "divider-color": "rgba(255, 255, 255, 0.12)",
  "primary-color": "#389638",
  "light-primary-color": "#6f956f",
  "label-badge-red": "var(--primary-color)",
  "paper-listbox-color": "#FFFFFF",
  "paper-toggle-button-checked-bar-color": "var(--light-primary-color)",
  "switch-unchecked-track-color": "var(--primary-text-color)",
  "card-background-color": "#4e4e4e",
  "label-badge-text-color": "var(--text-primary-color)",
  "primary-background-color": "#303030",
  "sidebar-icon-color": "var(--paper-item-icon-color)",
  "secondary-background-color": "#2b2b2b",
  "paper-item-icon-active-color": "#d8bf50",
  "switch-checked-color": "var(--primary-color)",
  "secondary-text-color": "#389638",
  "disabled-text-color": "#545454",
  "paper-item-icon_-_color": "var(--primary-text-color)",
  "paper-grey-200": "#191919",
  "primary-text-color": "#cfcfcf",
  "label-badge-background-color": "var(--secondary-background-color)",
});
