// This file is auto-generated from Home Assistant Core. Do not edit by hand.
// Regenerate with `script/gen_demo_core_data`.

// Integrations that provide the new style triggers and conditions. Their
// translations are part of the demo build.
export const automationPlatformDomains = [
  "air_quality",
  "alarm_control_panel",
  "assist_satellite",
  "battery",
  "button",
  "calendar",
  "climate",
  "counter",
  "cover",
  "door",
  "doorbell",
  "event",
  "fan",
  "garage_door",
  "gate",
  "humidifier",
  "humidity",
  "illuminance",
  "lawn_mower",
  "light",
  "lock",
  "media_player",
  "moisture",
  "moon",
  "motion",
  "occupancy",
  "power",
  "remote",
  "scene",
  "schedule",
  "select",
  "siren",
  "sun",
  "switch",
  "temperature",
  "text",
  "timer",
  "todo",
  "update",
  "vacuum",
  "valve",
  "vibration",
  "water_heater",
  "window",
  "zone",
];
