// This file is auto-generated from Home Assistant Core. Do not edit by hand.
// Regenerate with `script/gen_demo_core_data`.

export const triggerIcons = {
  air_quality: {
    co2_changed: { trigger: "mdi:molecule-co2" },
    co2_crossed_threshold: { trigger: "mdi:molecule-co2" },
    co_changed: { trigger: "mdi:molecule-co" },
    co_cleared: { trigger: "mdi:check-circle" },
    co_crossed_threshold: { trigger: "mdi:molecule-co" },
    co_detected: { trigger: "mdi:molecule-co" },
    gas_cleared: { trigger: "mdi:check-circle" },
    gas_detected: { trigger: "mdi:gas-cylinder" },
    n2o_changed: { trigger: "mdi:factory" },
    n2o_crossed_threshold: { trigger: "mdi:factory" },
    no2_changed: { trigger: "mdi:factory" },
    no2_crossed_threshold: { trigger: "mdi:factory" },
    no_changed: { trigger: "mdi:factory" },
    no_crossed_threshold: { trigger: "mdi:factory" },
    ozone_changed: { trigger: "mdi:weather-sunny-alert" },
    ozone_crossed_threshold: { trigger: "mdi:weather-sunny-alert" },
    pm10_changed: { trigger: "mdi:blur" },
    pm10_crossed_threshold: { trigger: "mdi:blur" },
    pm1_changed: { trigger: "mdi:blur" },
    pm1_crossed_threshold: { trigger: "mdi:blur" },
    pm25_changed: { trigger: "mdi:blur" },
    pm25_crossed_threshold: { trigger: "mdi:blur" },
    pm4_changed: { trigger: "mdi:blur" },
    pm4_crossed_threshold: { trigger: "mdi:blur" },
    smoke_cleared: { trigger: "mdi:check-circle" },
    smoke_detected: { trigger: "mdi:smoke-detector-variant" },
    so2_changed: { trigger: "mdi:factory" },
    so2_crossed_threshold: { trigger: "mdi:factory" },
    voc_changed: { trigger: "mdi:air-filter" },
    voc_crossed_threshold: { trigger: "mdi:air-filter" },
    voc_ratio_changed: { trigger: "mdi:air-filter" },
    voc_ratio_crossed_threshold: { trigger: "mdi:air-filter" },
  },
  alarm_control_panel: {
    armed: { trigger: "mdi:shield" },
    armed_away: { trigger: "mdi:shield-lock" },
    armed_home: { trigger: "mdi:shield-home" },
    armed_night: { trigger: "mdi:shield-moon" },
    armed_vacation: { trigger: "mdi:shield-airplane" },
    disarmed: { trigger: "mdi:shield-off" },
    triggered: { trigger: "mdi:bell-ring" },
  },
  assist_satellite: {
    idle: { trigger: "mdi:chat-sleep" },
    listening: { trigger: "mdi:chat-question" },
    processing: { trigger: "mdi:chat-processing" },
    responding: { trigger: "mdi:chat-alert" },
  },
  battery: {
    became_low: { trigger: "mdi:battery-alert" },
    level_changed: { trigger: "mdi:battery-unknown" },
    level_crossed_threshold: { trigger: "mdi:battery-alert" },
    no_longer_low: { trigger: "mdi:battery" },
    started_charging: { trigger: "mdi:battery-charging" },
    stopped_charging: { trigger: "mdi:battery" },
  },
  button: { pressed: { trigger: "mdi:gesture-tap-button" } },
  calendar: {
    event_ended: { trigger: "mdi:calendar-end" },
    event_started: { trigger: "mdi:calendar-start" },
  },
  climate: {
    hvac_mode_changed: { trigger: "mdi:thermostat" },
    started_cooling: { trigger: "mdi:snowflake" },
    started_drying: { trigger: "mdi:water-percent" },
    started_heating: { trigger: "mdi:fire" },
    target_humidity_changed: { trigger: "mdi:water-percent" },
    target_humidity_crossed_threshold: { trigger: "mdi:water-percent" },
    target_temperature_changed: { trigger: "mdi:thermometer" },
    target_temperature_crossed_threshold: { trigger: "mdi:thermometer" },
    turned_off: { trigger: "mdi:power-off" },
    turned_on: { trigger: "mdi:power-on" },
  },
  counter: {
    decremented: { trigger: "mdi:numeric-negative-1" },
    incremented: { trigger: "mdi:numeric-positive-1" },
    maximum_reached: { trigger: "mdi:sort-numeric-ascending-variant" },
    minimum_reached: { trigger: "mdi:sort-numeric-descending-variant" },
    reset: { trigger: "mdi:refresh" },
  },
  cover: {
    awning_closed: { trigger: "mdi:storefront-outline" },
    awning_opened: { trigger: "mdi:storefront-outline" },
    blind_closed: { trigger: "mdi:blinds-horizontal-closed" },
    blind_opened: { trigger: "mdi:blinds-horizontal" },
    curtain_closed: { trigger: "mdi:curtains-closed" },
    curtain_opened: { trigger: "mdi:curtains" },
    shade_closed: { trigger: "mdi:roller-shade-closed" },
    shade_opened: { trigger: "mdi:roller-shade" },
    shutter_closed: { trigger: "mdi:window-shutter" },
    shutter_opened: { trigger: "mdi:window-shutter-open" },
  },
  door: {
    closed: { trigger: "mdi:door-closed" },
    opened: { trigger: "mdi:door-open" },
  },
  doorbell: { rang: { trigger: "mdi:doorbell" } },
  event: { received: { trigger: "mdi:eye-check" } },
  fan: {
    turned_off: { trigger: "mdi:fan-off" },
    turned_on: { trigger: "mdi:fan" },
  },
  garage_door: {
    closed: { trigger: "mdi:garage" },
    opened: { trigger: "mdi:garage-open" },
  },
  gate: {
    closed: { trigger: "mdi:gate" },
    opened: { trigger: "mdi:gate-open" },
  },
  humidifier: {
    mode_changed: { trigger: "mdi:air-humidifier" },
    started_drying: { trigger: "mdi:arrow-down-bold" },
    started_humidifying: { trigger: "mdi:arrow-up-bold" },
    turned_off: { trigger: "mdi:air-humidifier-off" },
    turned_on: { trigger: "mdi:air-humidifier" },
  },
  humidity: {
    changed: { trigger: "mdi:water-percent" },
    crossed_threshold: { trigger: "mdi:water-percent" },
  },
  illuminance: {
    changed: { trigger: "mdi:brightness-6" },
    cleared: { trigger: "mdi:brightness-4" },
    crossed_threshold: { trigger: "mdi:brightness-6" },
    detected: { trigger: "mdi:brightness-7" },
  },
  lawn_mower: {
    became_idle: { trigger: "mdi:stop" },
    errored: { trigger: "mdi:alert-circle-outline" },
    paused_mowing: { trigger: "mdi:pause" },
    returned_to_dock: { trigger: "mdi:home-import-outline" },
    started_mowing: { trigger: "mdi:play" },
    started_returning: { trigger: "mdi:home-import-outline" },
  },
  light: {
    brightness_changed: { trigger: "mdi:lightbulb-on-50" },
    brightness_crossed_threshold: { trigger: "mdi:lightbulb-on-50" },
    turned_off: { trigger: "mdi:lightbulb-off" },
    turned_on: { trigger: "mdi:lightbulb-on" },
  },
  lock: {
    jammed: { trigger: "mdi:lock-alert" },
    locked: { trigger: "mdi:lock" },
    opened: { trigger: "mdi:lock-open-variant" },
    unlocked: { trigger: "mdi:lock-open-variant" },
  },
  media_player: {
    muted: { trigger: "mdi:volume-mute" },
    paused_playing: { trigger: "mdi:pause" },
    started_playing: { trigger: "mdi:play" },
    stopped_playing: { trigger: "mdi:stop" },
    turned_off: { trigger: "mdi:power" },
    turned_on: { trigger: "mdi:power" },
    unmuted: { trigger: "mdi:volume-high" },
    volume_changed: { trigger: "mdi:volume-medium" },
    volume_crossed_threshold: { trigger: "mdi:volume-medium" },
  },
  moisture: {
    changed: { trigger: "mdi:water-percent" },
    cleared: { trigger: "mdi:water-off" },
    crossed_threshold: { trigger: "mdi:water-percent" },
    detected: { trigger: "mdi:water" },
  },
  moon: { phase_changed: { trigger: "mdi:moon-waning-crescent" } },
  motion: {
    cleared: { trigger: "mdi:motion-sensor-off" },
    detected: { trigger: "mdi:motion-sensor" },
  },
  occupancy: {
    cleared: { trigger: "mdi:home-outline" },
    detected: { trigger: "mdi:home-account" },
  },
  power: {
    changed: { trigger: "mdi:flash" },
    crossed_threshold: { trigger: "mdi:flash" },
  },
  remote: {
    turned_off: { trigger: "mdi:remote-off" },
    turned_on: { trigger: "mdi:remote" },
  },
  scene: { activated: { trigger: "mdi:palette" } },
  schedule: {
    block_ended: { trigger: "mdi:calendar-blank" },
    block_started: { trigger: "mdi:calendar-clock" },
  },
  select: { selection_changed: { trigger: "mdi:format-list-bulleted" } },
  siren: {
    turned_off: { trigger: "mdi:bullhorn-outline" },
    turned_on: { trigger: "mdi:bullhorn" },
  },
  sun: {
    blue_hour_ended: { trigger: "mdi:weather-sunset" },
    blue_hour_started: { trigger: "mdi:weather-sunset" },
    dawn: { trigger: "mdi:weather-sunset-up" },
    dusk: { trigger: "mdi:weather-sunset-down" },
    elevation_changed: { trigger: "mdi:sun-angle" },
    elevation_crossed_threshold: { trigger: "mdi:sun-angle" },
    golden_hour_ended: { trigger: "mdi:weather-sunset" },
    golden_hour_started: { trigger: "mdi:weather-sunset" },
    midnight_sun_ended: { trigger: "mdi:weather-sunset" },
    midnight_sun_started: { trigger: "mdi:weather-sunny" },
    polar_night_ended: { trigger: "mdi:weather-sunset-up" },
    polar_night_started: { trigger: "mdi:weather-night" },
    solar_midnight: { trigger: "mdi:weather-night" },
    solar_noon: { trigger: "mdi:weather-sunny" },
    sunrise: { trigger: "mdi:weather-sunset-up" },
    sunset: { trigger: "mdi:weather-sunset-down" },
  },
  switch: {
    turned_off: { trigger: "mdi:toggle-switch-variant-off" },
    turned_on: { trigger: "mdi:toggle-switch-variant" },
  },
  temperature: {
    changed: { trigger: "mdi:thermometer" },
    crossed_threshold: { trigger: "mdi:thermometer" },
  },
  text: { changed: { trigger: "mdi:form-textbox" } },
  timer: {
    cancelled: { trigger: "mdi:timer-cancel" },
    finished: { trigger: "mdi:timer-check" },
    paused: { trigger: "mdi:timer-pause" },
    remaining_time_reached: { trigger: "mdi:timer-alert-outline" },
    restarted: { trigger: "mdi:timer-refresh" },
    started: { trigger: "mdi:timer-play" },
  },
  todo: {
    item_added: { trigger: "mdi:clipboard-plus" },
    item_completed: { trigger: "mdi:clipboard-check" },
    item_removed: { trigger: "mdi:clipboard-minus" },
  },
  update: { became_available: { trigger: "mdi:package-up" } },
  vacuum: {
    errored: { trigger: "mdi:alert-circle-outline" },
    paused_cleaning: { trigger: "mdi:pause" },
    returned_to_dock: { trigger: "mdi:home-outline" },
    started_cleaning: { trigger: "mdi:play" },
    started_returning: { trigger: "mdi:home-import-outline" },
  },
  valve: {
    closed: { trigger: "mdi:valve-closed" },
    opened: { trigger: "mdi:valve-open" },
  },
  vibration: {
    cleared: { trigger: "mdi:vibrate-off" },
    detected: { trigger: "mdi:vibrate" },
  },
  water_heater: {
    operation_mode_changed: { trigger: "mdi:water-boiler" },
    target_temperature_changed: { trigger: "mdi:thermometer" },
    target_temperature_crossed_threshold: { trigger: "mdi:thermometer" },
    turned_off: { trigger: "mdi:water-boiler-off" },
    turned_on: { trigger: "mdi:water-boiler" },
  },
  window: {
    closed: { trigger: "mdi:window-closed" },
    opened: { trigger: "mdi:window-open" },
  },
  zone: {
    entered: { trigger: "mdi:map-marker-plus" },
    left: { trigger: "mdi:map-marker-minus" },
    occupancy_cleared: { trigger: "mdi:account-off" },
    occupancy_detected: { trigger: "mdi:account-group" },
  },
};

export const conditionIcons = {
  air_quality: {
    is_co2_value: { condition: "mdi:molecule-co2" },
    is_co_cleared: { condition: "mdi:check-circle" },
    is_co_detected: { condition: "mdi:molecule-co" },
    is_co_value: { condition: "mdi:molecule-co" },
    is_gas_cleared: { condition: "mdi:check-circle" },
    is_gas_detected: { condition: "mdi:gas-cylinder" },
    is_n2o_value: { condition: "mdi:factory" },
    is_no2_value: { condition: "mdi:factory" },
    is_no_value: { condition: "mdi:factory" },
    is_ozone_value: { condition: "mdi:weather-sunny-alert" },
    is_pm10_value: { condition: "mdi:blur" },
    is_pm1_value: { condition: "mdi:blur" },
    is_pm25_value: { condition: "mdi:blur" },
    is_pm4_value: { condition: "mdi:blur" },
    is_smoke_cleared: { condition: "mdi:check-circle" },
    is_smoke_detected: { condition: "mdi:smoke-detector-variant" },
    is_so2_value: { condition: "mdi:factory" },
    is_voc_ratio_value: { condition: "mdi:air-filter" },
    is_voc_value: { condition: "mdi:air-filter" },
  },
  alarm_control_panel: {
    is_armed: { condition: "mdi:shield" },
    is_armed_away: { condition: "mdi:shield-lock" },
    is_armed_home: { condition: "mdi:shield-home" },
    is_armed_night: { condition: "mdi:shield-moon" },
    is_armed_vacation: { condition: "mdi:shield-airplane" },
    is_disarmed: { condition: "mdi:shield-off" },
    is_triggered: { condition: "mdi:bell-ring" },
  },
  assist_satellite: {
    is_idle: { condition: "mdi:chat-sleep" },
    is_listening: { condition: "mdi:chat-question" },
    is_processing: { condition: "mdi:chat-processing" },
    is_responding: { condition: "mdi:chat-alert" },
  },
  battery: {
    is_charging: { condition: "mdi:battery-charging" },
    is_level: { condition: "mdi:battery-unknown" },
    is_low: { condition: "mdi:battery-alert" },
    is_not_charging: { condition: "mdi:battery" },
    is_not_low: { condition: "mdi:battery" },
  },
  calendar: { is_event_active: { condition: "mdi:calendar-check" } },
  climate: {
    is_cooling: { condition: "mdi:snowflake" },
    is_drying: { condition: "mdi:water-percent" },
    is_heating: { condition: "mdi:fire" },
    is_hvac_mode: { condition: "mdi:thermostat" },
    is_off: { condition: "mdi:power-off" },
    is_on: { condition: "mdi:power-on" },
    is_target_humidity: { condition: "mdi:water-percent" },
    is_target_temperature: { condition: "mdi:thermometer" },
  },
  counter: { is_value: { condition: "mdi:counter" } },
  cover: {
    awning_is_closed: { condition: "mdi:storefront-outline" },
    awning_is_open: { condition: "mdi:storefront-outline" },
    blind_is_closed: { condition: "mdi:blinds-horizontal-closed" },
    blind_is_open: { condition: "mdi:blinds-horizontal" },
    curtain_is_closed: { condition: "mdi:curtains-closed" },
    curtain_is_open: { condition: "mdi:curtains" },
    shade_is_closed: { condition: "mdi:roller-shade-closed" },
    shade_is_open: { condition: "mdi:roller-shade" },
    shutter_is_closed: { condition: "mdi:window-shutter" },
    shutter_is_open: { condition: "mdi:window-shutter-open" },
  },
  door: {
    is_closed: { condition: "mdi:door-closed" },
    is_open: { condition: "mdi:door-open" },
  },
  fan: {
    is_off: { condition: "mdi:fan-off" },
    is_on: { condition: "mdi:fan" },
  },
  garage_door: {
    is_closed: { condition: "mdi:garage" },
    is_open: { condition: "mdi:garage-open" },
  },
  gate: {
    is_closed: { condition: "mdi:gate" },
    is_open: { condition: "mdi:gate-open" },
  },
  humidifier: {
    is_drying: { condition: "mdi:arrow-down-bold" },
    is_humidifying: { condition: "mdi:arrow-up-bold" },
    is_mode: { condition: "mdi:air-humidifier" },
    is_off: { condition: "mdi:air-humidifier-off" },
    is_on: { condition: "mdi:air-humidifier" },
    is_target_humidity: { condition: "mdi:water-percent" },
  },
  humidity: { is_value: { condition: "mdi:water-percent" } },
  illuminance: {
    is_detected: { condition: "mdi:brightness-7" },
    is_not_detected: { condition: "mdi:brightness-4" },
    is_value: { condition: "mdi:brightness-percent" },
  },
  lawn_mower: {
    is_docked: { condition: "mdi:home-import-outline" },
    is_encountering_an_error: { condition: "mdi:alert-circle-outline" },
    is_idle: { condition: "mdi:stop" },
    is_mowing: { condition: "mdi:play" },
    is_paused: { condition: "mdi:pause" },
    is_returning: { condition: "mdi:home-import-outline" },
  },
  light: {
    is_brightness: { condition: "mdi:lightbulb-on-50" },
    is_off: { condition: "mdi:lightbulb-off" },
    is_on: { condition: "mdi:lightbulb-on" },
  },
  lock: {
    is_jammed: { condition: "mdi:lock-alert" },
    is_locked: { condition: "mdi:lock" },
    is_open: { condition: "mdi:lock-open-variant" },
    is_unlocked: { condition: "mdi:lock-open-variant" },
  },
  media_player: {
    is_muted: { condition: "mdi:volume-mute" },
    is_not_playing: { condition: "mdi:stop" },
    is_off: { condition: "mdi:cast-off" },
    is_on: { condition: "mdi:cast" },
    is_paused: { condition: "mdi:pause" },
    is_playing: { condition: "mdi:play" },
    is_unmuted: { condition: "mdi:volume-high" },
    is_volume: { condition: "mdi:volume-medium" },
  },
  moisture: {
    is_detected: { condition: "mdi:water" },
    is_not_detected: { condition: "mdi:water-off" },
    is_value: { condition: "mdi:water-percent" },
  },
  moon: {
    is_phase: { condition: "mdi:moon-full" },
    is_waning: { condition: "mdi:moon-waning-crescent" },
    is_waxing: { condition: "mdi:moon-waxing-crescent" },
  },
  motion: {
    is_detected: { condition: "mdi:motion-sensor" },
    is_not_detected: { condition: "mdi:motion-sensor-off" },
  },
  occupancy: {
    is_detected: { condition: "mdi:home-account" },
    is_not_detected: { condition: "mdi:home-outline" },
  },
  power: { is_value: { condition: "mdi:flash" } },
  remote: {
    is_off: { condition: "mdi:remote-off" },
    is_on: { condition: "mdi:remote" },
  },
  schedule: {
    is_off: { condition: "mdi:calendar-blank" },
    is_on: { condition: "mdi:calendar-clock" },
  },
  select: { is_option_selected: { condition: "mdi:format-list-bulleted" } },
  siren: {
    is_off: { condition: "mdi:bullhorn-outline" },
    is_on: { condition: "mdi:bullhorn" },
  },
  sun: {
    elevation: { condition: "mdi:sun-angle" },
    is_ascending: { condition: "mdi:weather-sunset-up" },
    is_blue_hour: { condition: "mdi:weather-sunset" },
    is_descending: { condition: "mdi:weather-sunset-down" },
    is_evening_twilight: { condition: "mdi:weather-sunset-down" },
    is_golden_hour: { condition: "mdi:weather-sunset" },
    is_midnight_sun: { condition: "mdi:weather-sunny" },
    is_morning_twilight: { condition: "mdi:weather-sunset-up" },
    is_night: { condition: "mdi:weather-night" },
    is_polar_night: { condition: "mdi:weather-night" },
    is_set: { condition: "mdi:weather-sunny-off" },
    is_up: { condition: "mdi:weather-sunny" },
  },
  switch: {
    is_off: { condition: "mdi:toggle-switch-variant-off" },
    is_on: { condition: "mdi:toggle-switch-variant" },
  },
  temperature: { is_value: { condition: "mdi:thermometer" } },
  text: { is_equal_to: { condition: "mdi:form-textbox" } },
  timer: {
    is_active: { condition: "mdi:timer" },
    is_idle: { condition: "mdi:timer-off" },
    is_paused: { condition: "mdi:timer-pause" },
  },
  todo: {
    all_completed: { condition: "mdi:clipboard-check" },
    incomplete: { condition: "mdi:clipboard-alert" },
  },
  update: {
    is_available: { condition: "mdi:package-up" },
    is_not_available: { condition: "mdi:package" },
  },
  vacuum: {
    is_cleaning: { condition: "mdi:play" },
    is_docked: { condition: "mdi:home-import-outline" },
    is_encountering_an_error: { condition: "mdi:alert-circle-outline" },
    is_paused: { condition: "mdi:pause" },
    is_returning: { condition: "mdi:home-import-outline" },
  },
  valve: {
    is_closed: { condition: "mdi:valve-closed" },
    is_open: { condition: "mdi:valve-open" },
  },
  vibration: {
    is_detected: { condition: "mdi:vibrate" },
    is_not_detected: { condition: "mdi:vibrate-off" },
  },
  water_heater: {
    is_off: { condition: "mdi:water-boiler-off" },
    is_on: { condition: "mdi:water-boiler" },
    is_operation_mode: { condition: "mdi:water-boiler" },
    is_target_temperature: { condition: "mdi:thermometer" },
  },
  window: {
    is_closed: { condition: "mdi:window-closed" },
    is_open: { condition: "mdi:window-open" },
  },
  zone: {
    in_zone: { condition: "mdi:map-marker-check" },
    not_in_zone: { condition: "mdi:map-marker-remove" },
    occupancy_is_detected: { condition: "mdi:account-group" },
    occupancy_is_not_detected: { condition: "mdi:account-off" },
  },
};
