import type { DeviceRegistryEntry } from "../../../src/data/device/device_registry";

const baseDevice = {
  config_entries_subentries: {},
  connections: [] as [string, string][],
  identifiers: [] as [string, string][],
  model_id: null,
  labels: [] as string[],
  sw_version: null,
  hw_version: null,
  serial_number: null,
  via_device_id: null,
  area_id: null,
  name_by_user: null,
  disabled_by: null,
  configuration_url: null,
  parent_device_id: null,
  created_at: 0,
  modified_at: 0,
};

export const demoDevices: DeviceRegistryEntry[] = [
  {
    ...baseDevice,
    id: "co2signal",
    name: "Electricity Maps",
    manufacturer: "Electricity Maps",
    model: "CO2 Signal",
    config_entries: ["co2signal"],
    primary_config_entry: "co2signal",
    entry_type: "service",
  },
  {
    ...baseDevice,
    id: "hue-bridge",
    name: "Philips Hue Bridge",
    manufacturer: "Signify",
    model: "Hue Bridge (BSB002)",
    sw_version: "1.50.0",
    config_entries: ["mock-hue"],
    primary_config_entry: "mock-hue",
    entry_type: null,
  },
  {
    ...baseDevice,
    id: "sonos-living",
    name: "Living Room",
    manufacturer: "Sonos",
    model: "One",
    config_entries: ["mock-sonos"],
    primary_config_entry: "mock-sonos",
    entry_type: null,
  },
  {
    ...baseDevice,
    id: "power-strip",
    name: "Power strip",
    manufacturer: "Acme",
    model: "Smart Power Strip",
    config_entries: ["mock-hue"],
    primary_config_entry: "mock-hue",
    entry_type: null,
  },
  // Child devices (logical parts of the power strip). They carry the parent's
  // inherited hardware fields, mirroring how resolveChildDevices fills them in
  // from the WebSocket, and reference the parent via parent_device_id.
  {
    ...baseDevice,
    id: "power-strip-outlet-1",
    name: "Outlet 1",
    manufacturer: "Acme",
    model: "Smart Power Strip",
    config_entries: ["mock-hue"],
    primary_config_entry: "mock-hue",
    entry_type: null,
    parent_device_id: "power-strip",
  },
  {
    ...baseDevice,
    id: "power-strip-outlet-2",
    name: "Outlet 2",
    manufacturer: "Acme",
    model: "Smart Power Strip",
    config_entries: ["mock-hue"],
    primary_config_entry: "mock-hue",
    entry_type: null,
    parent_device_id: "power-strip",
  },
  {
    ...baseDevice,
    id: "matter-bulb",
    name: "Office bulb",
    manufacturer: "Nanoleaf",
    model: "Essentials A19",
    sw_version: "3.5.9",
    config_entries: ["mock-matter"],
    primary_config_entry: "mock-matter",
    entry_type: null,
  },
  {
    ...baseDevice,
    id: "matter-plug",
    name: "Office plug",
    manufacturer: "Eve",
    model: "Energy",
    sw_version: "3.2.0",
    config_entries: ["mock-matter"],
    primary_config_entry: "mock-matter",
    entry_type: null,
  },
  {
    ...baseDevice,
    id: "zha-motion",
    name: "Hallway motion",
    manufacturer: "IKEA of Sweden",
    model: "TRADFRI motion sensor",
    config_entries: ["mock-zha"],
    primary_config_entry: "mock-zha",
    entry_type: null,
  },
  {
    ...baseDevice,
    id: "zha-remote",
    name: "Bedroom remote",
    manufacturer: "IKEA of Sweden",
    model: "TRADFRI on/off switch",
    config_entries: ["mock-zha"],
    primary_config_entry: "mock-zha",
    entry_type: null,
  },
  {
    ...baseDevice,
    id: "zwave-dimmer",
    name: "Dining room dimmer",
    manufacturer: "Fibaro",
    model: "Dimmer 2",
    sw_version: "3.5",
    config_entries: ["mock-zwave-js"],
    primary_config_entry: "mock-zwave-js",
    entry_type: null,
  },
  {
    ...baseDevice,
    id: "rf-bridge",
    name: "RF bridge",
    manufacturer: "SONOFF",
    model: "RF Bridge R2",
    config_entries: ["mock-mqtt"],
    primary_config_entry: "mock-mqtt",
    entry_type: null,
  },
  {
    ...baseDevice,
    id: "ir-blaster",
    name: "Living room IR blaster",
    manufacturer: "Broadlink",
    model: "RM4 pro",
    config_entries: ["mock-broadlink"],
    primary_config_entry: "mock-broadlink",
    entry_type: null,
  },
];
