import type { DeviceRegistryEntry } from "../../../src/data/device/device_registry";

const baseDevice = {
  config_entries_subentries: {},
  connections: [] as [string, string][],
  identifiers: [] as [string, string][],
  model_id: null,
  labels: [] as string[],
  sw_version: null,
  hw_version: null,
  serial_number: null,
  via_device_id: null,
  area_id: null,
  name_by_user: null,
  disabled_by: null,
  configuration_url: null,
  config_entry_id: null,
  config_subentry_id: null,
  created_at: 0,
  modified_at: 0,
};

export const demoDevices: DeviceRegistryEntry[] = [
  {
    ...baseDevice,
    id: "co2signal",
    name: "Electricity Maps",
    manufacturer: "Electricity Maps",
    model: "CO2 Signal",
    config_entries: ["co2signal"],
    primary_config_entry: "co2signal",
    entry_type: "service",
  },
  {
    ...baseDevice,
    id: "hue-bridge",
    name: "Philips Hue Bridge",
    manufacturer: "Signify",
    model: "Hue Bridge (BSB002)",
    sw_version: "1.50.0",
    config_entries: ["mock-hue"],
    primary_config_entry: "mock-hue",
    entry_type: null,
  },
  {
    ...baseDevice,
    id: "sonos-living",
    name: "Living Room",
    manufacturer: "Sonos",
    model: "One",
    config_entries: ["mock-sonos"],
    primary_config_entry: "mock-sonos",
    entry_type: null,
  },
];
