import { MockHomeAssistant } from "../../../src/fake_data/provide_hass";

export const mockSensor = (hass: MockHomeAssistant) => {
  hass.mockWS("sensor/numeric_device_classes", () => [
    {
      numeric_device_classes: [
        "volume_storage",
        "gas",
        "data_size",
        "irradiance",
        "wind_speed",
        "volatile_organic_compounds",
        "volatile_organic_compounds_parts",
        "voltage",
        "frequency",
        "precipitation_intensity",
        "volume",
        "precipitation",
        "battery",
        "nitrogen_dioxide",
        "speed",
        "signal_strength",
        "pm1",
        "nitrous_oxide",
        "atmospheric_pressure",
        "data_rate",
        "temperature",
        "power_factor",
        "aqi",
        "current",
        "volume_flow_rate",
        "humidity",
        "duration",
        "ozone",
        "distance",
        "pressure",
        "pm25",
        "weight",
        "energy",
        "carbon_monoxide",
        "apparent_power",
        "illuminance",
        "energy_storage",
        "moisture",
        "power",
        "water",
        "carbon_dioxide",
        "ph",
        "reactive_power",
        "monetary",
        "nitrogen_monoxide",
        "pm10",
        "sound_pressure",
        "sulphur_dioxide",
      ],
    },
  ]);
};
