#!/bin/sh
# Resolve all frontend dependencies that the application requires to develop.

# Stop on errors
set -e

cd "$(dirname "$0")/.."

# Install node modules
yarn install

# Install bower web components. Allow to download the components as root since the user in docker is root.
./node_modules/.bin/bower install --allow-root

# Generate all needed files.
script/build_frontend

# Build files that need to be generated to run development mode
./node_modules/.bin/gulp gen-service-worker
