#!/bin/sh
# Builds the frontend for production

# Stop on errors
set -e

cd "$(dirname "$0")/.."

rm -rf final
cp -r public final

# Build frontend
# BUILD_DEV=0 ./node_modules/.bin/gulp

# Entry points
cp build/*.js build/*.html final

# Panels
mkdir final/panels
cp build/panels/*.html final/panels

# Local Roboto
cp -r bower_components/font-roboto-local/fonts final

# Polyfill web components
cp bower_components/webcomponentsjs/webcomponents-lite.js final
cp bower_components/webcomponentsjs/custom-elements-es5-adapter.js final

# Icons
script/update_mdi.py

# Leaflet
mkdir final/images/leaflet
cp bower_components/leaflet/dist/leaflet.css final/images/leaflet
cp -r bower_components/leaflet/dist/images final/images/leaflet/

# Generate service worker
BUILD_DEV=0 ./node_modules/.bin/gulp gen-service-worker
cp build/service_worker.js final


# GZIP frontend
cd final
gzip -f -n -k -9 *.html *.js ./panels/*.html ./fonts/roboto/*.ttf ./fonts/robotomono/*.ttf
cd ..

# Generate the MD5 hash of the new frontend
script/fingerprint_frontend.py
