#!/bin/sh
# Helper to start Home Assistant Core inside the devcontainer

# Stop on errors
set -e

if [ -z "${DEVCONTAINER}" ]; then
  echo "This task should only run inside a devcontainer, for local install HA Core in a venv."
  exit 1
fi

if [ ! -z "${CODESPACES}" ]; then
  WORKSPACE="/root/workspace/frontend"
else
  WORKSPACE="/workspaces/frontend"
fi

if [ -z $(which hass) ]; then
  echo "Installing Home Asstant core from dev."
  python3 -m pip install --upgrade \
    colorlog \
    git+git://github.com/home-assistant/home-assistant.git@dev
fi

if [ ! -d "${WORKSPACE}/config" ]; then
  echo "Creating default configuration."
  mkdir -p "${WORKSPACE}/config";
  cp "${WORKSPACE}/.devcontainer/example_configuration.yaml" "${WORKSPACE}/config/configuration.yaml"

  echo "" | tee -a "${WORKSPACE}/config/configuration.yaml"

  if [ ! -z "${HASSIO}" ]; then
    echo "# frontend:" | tee -a "${WORKSPACE}/config/configuration.yaml"
    echo "#   development_repo: ${WORKSPACE}" | tee -a "${WORKSPACE}/config/configuration.yaml"
    echo "" | tee -a "${WORKSPACE}/config/configuration.yaml"
    echo "hassio:" | tee -a "${WORKSPACE}/config/configuration.yaml"
    echo "  development_repo: ${WORKSPACE}" | tee -a "${WORKSPACE}/config/configuration.yaml"
  else
    echo "frontend:" | tee -a "${WORKSPACE}/config/configuration.yaml"
    echo "  development_repo: ${WORKSPACE}" | tee -a "${WORKSPACE}/config/configuration.yaml"
    echo "" | tee -a "${WORKSPACE}/config/configuration.yaml"
    echo "# hassio:" | tee -a "${WORKSPACE}/config/configuration.yaml"
    echo "#   development_repo: ${WORKSPACE}" | tee -a "${WORKSPACE}/config/configuration.yaml"
  fi

  for file in "groups" "automations" "scripts" "scenes"; do
    touch "${WORKSPACE}/config/${file}.yaml"
  done

fi

hass -c "${WORKSPACE}/config"
