#!/usr/bin/env bash
#
# This script can be used to develop and test the frontend without having to
# link the build in a running core instance through the frontend/development_repo setting.
#
# WARNING:
# If you have an active login session in the frontend. The core that was used
# as a backend during the time of the login remains used until you logout again.
# So if you reuse the url hosting the frontend, you will need to logout before
# it will actually start using the core backend configured by this script.
#
# If you run this script without parameters, the frontend will be accessible under http://localhost:8124.
# And it will use the core instance running under http://localhost:8123 as a backend.
# Note that from a devcontainer, the frontend will be accessible under port 8124 on the host container.
# Inside the devcontainer it will be accessible under port 8123 instead.
# The core instance endpoint remains the same in both cases, as this is resolved from the browser.
#
# You can change the core instance the frontend connects to by passing the -c option.
# For example: script/develop_and_serve -c https://myhost.duckdns.org:8123
# This will also work for existing production core instances.
# It does not need to be a development version hosted locally.
# However note that if the core you connect to uses https, you will also need to use
# https to connect to your local development frontend. A self signed certificate
# for localhost is included and will be used when necessary. You just have to accept
# it as valid when browsing to your local development frontend.
#
# You can change the port the frontend is served on by passing the -p option.
# For example: script/develop_and_serve -p 8654
# Note that if you are running from a devcontainer, you will need to setup
# port forwarding as well if you want to access it from the container host.

# Stop on errors
set -e

cd "$(dirname "$0")/.."

if [ ! -d "./hassio/build" ]; then
  echo Building hassio
  # the hassio rest app doesn't need the HASS_URL override,
  # it will use the url from the current login session
  hassio/script/build_hassio
fi

./script/develop &

if [ -n "$DEVCONTAINER" ]; then
    nodeCoreUrl="${coreUrl/localhost/host.docker.internal}"
else
    nodeCoreUrl="$coreUrl"
fi
yarn serve "$@"