#!/bin/sh
# Pushes a new version to PyPi.

# Stop on errors
set -e

cd "$(dirname "$0")/.."

# Install node modules
yarn install

script/build_frontend

rm -rf dist
python3 setup.py sdist
python3 -m twine upload dist/* --skip-existing
