#!/bin/sh
# Setup translation fetching during development

# Stop on errors
set -e

cd "$(dirname "$0")/.."

node --import ./ts-node-register.js ./node_modules/.bin/gulp setup-and-fetch-nightly-translations