#!/bin/sh
# Builds the Hass.io app for production

# Stop on errors
set -e

cd "$(dirname "$0")/.."

OUTPUT_DIR_ES5=build-es5

rm -rf $OUTPUT_DIR_ES5
NODE_ENV=production ../node_modules/.bin/webpack -p
node script/gen-index-html.js
