import type { maplibreGL } from "@maplibre/maplibre-gl-leaflet";
import type { Map as LeafletMap, TileLayerOptions } from "leaflet";
import type { setRTLTextPlugin, StyleSpecification } from "maplibre-gl";
import type { LeafletModuleType } from "../dom/setup-leaflet-map";
import {
  MAP_TILES_PATH,
  mapTilesUrl,
  refreshMapTilesToken,
  subscribeMapTilesToken,
  withMapTilesToken,
} from "../../data/map_tiles";

// Generated by build-scripts/gulp/map-assets.js. The attribution comes from the
// TileJSON, deliberately: it follows whoever serves the tiles.
const VECTOR_STYLES = {
  light: "/static/map/light.json",
  dark: "/static/map/dark.json",
} as const;

// Without it Arabic and Hebrew labels render reversed. Loaded by MapLibre's
// worker, hence a URL rather than an import.
const RTL_TEXT_PLUGIN_URL = "/static/map/mapbox-gl-rtl-text.js";

// MapLibre needs WebGL2 even for raster, so the fallback stays a Leaflet layer.
// OSM serves no @2x variant.
const RASTER_TILE_URL = `${MAP_TILES_PATH}/raster/{z}/{x}/{y}.png?token={token}`;
// The demo has no proxy to go through. Upstream serves raster to a browser that
// identifies itself with a referrer, which the demo page's `same-origin` meta
// policy strips again unless the tiles ask for it back.
const DEMO_RASTER_TILE_URL = "https://tile.openstreetmap.org/{z}/{x}/{y}.png";
const OSM_ATTRIBUTION =
  '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors';

// Browsers keep about 16 live WebGL contexts and drop the oldest, which a
// dashboard full of map cards hits. A transient loss is restored, hence a grace.
const CONTEXT_RESTORE_GRACE = 2000;
const RECOVERY_THROTTLE = 30000;

// On the map, not the layer: marker clustering throws without a maximum. The
// floor is 1 because at Leaflet zoom 0 the adapter drives MapLibre to -1.
export const MAP_MIN_ZOOM = 1;
export const MAP_MAX_ZOOM = 20;
// OSM's raster stops at 19 and the proxy refuses higher, so Leaflet scales the
// last level up rather than asking for tiles that are not there.
const RASTER_MAX_NATIVE_ZOOM = 19;

// Leaflet substitutes any option into the URL template; its types do not.
type TokenTileLayerOptions = TileLayerOptions & { token?: string };

export interface MapBaseLayer {
  // A no-op for raster, which has no dark variant and is inverted in CSS.
  setDarkMode: (darkMode: boolean) => void;
}

let webGL2Supported: boolean | undefined;

// Rules out iOS below 15, older Android tablets and blocklisted drivers.
const supportsWebGL2 = (): boolean => {
  if (webGL2Supported === undefined) {
    try {
      const context = document.createElement("canvas").getContext("webgl2");
      webGL2Supported = Boolean(context);
      // Contexts are scarce; the probe must not keep one.
      context?.getExtension("WEBGL_lose_context")?.loseContext();
    } catch {
      webGL2Supported = false;
    }
  }
  return webGL2Supported;
};

// MapLibre rejects a relative sprite URL. Not the glyph URL: encoding would
// mangle its {fontstack} and {range} placeholders.
// The demo has no core to proxy through. OSM sets CORS on its tiles but not on
// its glyphs and sprites, which is why those come from VersaTiles.
const DEMO_UPSTREAM = {
  tilejson: "https://vector.openstreetmap.org/shortbread_v1/tilejson.json",
  assets: "https://tiles.versatiles.org/assets",
};

const useDemoUpstream = (style: StyleSpecification): StyleSpecification => {
  style.glyphs = `${DEMO_UPSTREAM.assets}/glyphs/{fontstack}/{range}.pbf`;
  style.sprite = [
    { id: "basics", url: `${DEMO_UPSTREAM.assets}/sprites/basics/sprites` },
  ];
  Object.values(style.sources).forEach((source) => {
    if ("url" in source) {
      source.url = DEMO_UPSTREAM.tilejson;
    }
  });
  return style;
};

const loadStyle = async (url: string): Promise<StyleSpecification> => {
  const style: StyleSpecification = await (await fetch(url)).json();

  if (__DEMO__) {
    return useDemoUpstream(style);
  }

  if (typeof style.sprite === "string") {
    style.sprite = mapTilesUrl(style.sprite);
  } else if (Array.isArray(style.sprite)) {
    style.sprite = style.sprite.map((sprite) => ({
      ...sprite,
      url: mapTilesUrl(sprite.url),
    }));
  }
  return style;
};

// Global to MapLibre, and it throws when set twice.
let rtlTextPluginRequested = false;
const ensureRTLTextPlugin = (setPlugin: typeof setRTLTextPlugin) => {
  if (rtlTextPluginRequested) {
    return;
  }
  rtlTextPluginRequested = true;
  setPlugin(new URL(RTL_TEXT_PLUGIN_URL, location.href).href, true).catch(
    () => {
      // RTL labels stay reversed; everything else still renders.
    }
  );
};

const createVectorLayer = async (
  createLayer: typeof maplibreGL,
  leaflet: LeafletModuleType,
  map: LeafletMap,
  darkMode: boolean,
  token: string | undefined
): Promise<MapBaseLayer | undefined> => {
  let layer: ReturnType<typeof maplibreGL> | undefined;

  try {
    layer = createLayer({
      style: await loadStyle(VECTOR_STYLES[darkMode ? "dark" : "light"]),
      // Absolute, or the worker fetching tiles cannot resolve them.
      transformRequest: (url) => ({
        url: withMapTilesToken(url),
        // OSM asks a website for a referrer, and the demo has no instance
        // hostname to leak.
        referrerPolicy: __DEMO__ ? "origin" : undefined,
      }),
    });
    // The plugin builds the MapLibre map in `onAdd`, so a refused context or a
    // blocked worker throws here. Keep it guarded or those lose the fallback.
    layer.addTo(map);
  } catch {
    if (layer) {
      try {
        layer.remove();
      } catch {
        // May never have finished being added.
      }
    }
    return undefined;
  }

  // Tracked apart so a failed request rolls back to what is displayed, not to
  // the opposite of what it asked - which with several in flight differs.
  let appliedDarkMode = darkMode;
  let requestedDarkMode = darkMode;
  // Styles are fetched, so only the newest request may touch the map.
  let latestRequest = 0;
  let vector = true;
  let refused = false;

  const glMap = layer.getMaplibreMap();
  let fallbackTimeout: number | undefined;
  let contextLost = false;

  // Declared first, but only ever called once all three exist.
  const handleVisibilityChange = () => {
    if (contextLost) {
      scheduleSwap();
    }
  };

  const swapToRaster = () => {
    vector = false;
    document.removeEventListener("visibilitychange", handleVisibilityChange);
    try {
      layer.remove();
    } catch {
      // Nothing left to detach.
    }
    createRasterLayer(leaflet, map, token);
  };

  const scheduleSwap = () => {
    clearTimeout(fallbackTimeout);
    // Backgrounding drops it too, and there it comes back on return.
    if (!vector || document.hidden) {
      return;
    }
    fallbackTimeout = window.setTimeout(swapToRaster, CONTEXT_RESTORE_GRACE);
  };

  glMap.on("webglcontextlost", () => {
    contextLost = true;
    scheduleSwap();
  });
  glMap.on("webglcontextrestored", () => {
    contextLost = false;
    clearTimeout(fallbackTimeout);
  });
  document.addEventListener("visibilitychange", handleVisibilityChange);

  map.on("unload", () => {
    // Otherwise the timer revives a map that is already gone.
    clearTimeout(fallbackTimeout);
    document.removeEventListener("visibilitychange", handleVisibilityChange);
  });

  const applyStyle = (newDarkMode: boolean) => {
    const request = ++latestRequest;

    loadStyle(VECTOR_STYLES[newDarkMode ? "dark" : "light"])
      .then((style) => {
        if (request === latestRequest) {
          appliedDarkMode = newDarkMode;
          layer.getMaplibreMap()?.setStyle(style);
        }
      })
      .catch(() => {
        if (request === latestRequest) {
          requestedDarkMode = appliedDarkMode;
        }
      });
  };

  // A refused request leaves the source dead: the TileJSON is fetched once and
  // is never retried, so the style has to be applied again once there is a new
  // token. Throttled, or a proxy refusing for another reason loops.
  let lastRecovery = 0;
  glMap.on("error", (event) => {
    const status = (event.error as { status?: number } | undefined)?.status;
    // 403 is a stale token, 404 the proxy not registered yet during a restart,
    // and no status at all a network failure. All three recover the same way,
    // and a token that comes back unchanged costs nothing.
    if (status !== undefined && status !== 403 && status !== 404) {
      return;
    }
    if (Date.now() - lastRecovery < RECOVERY_THROTTLE) {
      return;
    }
    lastRecovery = Date.now();
    refused = true;
    refreshMapTilesToken();
  });

  // Only a new token clears the refusal. A theme change in between applies a
  // style that is refused just as the last one was, so it proves nothing.
  const unsubscribeToken = subscribeMapTilesToken(() => {
    if (vector && refused) {
      refused = false;
      applyStyle(requestedDarkMode);
    }
  });
  map.on("unload", unsubscribeToken);

  return {
    setDarkMode: (newDarkMode: boolean) => {
      if (!vector || newDarkMode === requestedDarkMode) {
        return;
      }
      requestedDarkMode = newDarkMode;
      applyStyle(newDarkMode);
    },
  };
};

const createRasterLayer = (
  leaflet: LeafletModuleType,
  map: LeafletMap,
  token: string | undefined
): MapBaseLayer => {
  const layer = leaflet
    .tileLayer(__DEMO__ ? DEMO_RASTER_TILE_URL : mapTilesUrl(RASTER_TILE_URL), {
      attribution: OSM_ATTRIBUTION,
      maxZoom: MAP_MAX_ZOOM,
      maxNativeZoom: RASTER_MAX_NATIVE_ZOOM,
      referrerPolicy: __DEMO__ ? "origin" : undefined,
      // Leaflet throws on an undefined template variable, so no token means an
      // empty one: the tiles 403 and the markers still draw.
      token: token ?? "",
    } as TokenTileLayerOptions)
    .addTo(map);

  // Substituted per request, so a refreshed token needs no new layer.
  const unsubscribe = subscribeMapTilesToken((newToken) => {
    (layer.options as TokenTileLayerOptions).token = newToken;
    // Tiles that 403'd are cached as failures; only a redraw asks again.
    layer.redraw();
  });
  map.on("unload", unsubscribe);

  return { setDarkMode: () => undefined };
};

export const createBaseLayer = async (
  leaflet: LeafletModuleType,
  map: LeafletMap,
  darkMode: boolean,
  token: string | undefined
): Promise<MapBaseLayer> => {
  if (supportsWebGL2()) {
    let vectorLayer: MapBaseLayer | undefined;
    try {
      const [{ maplibreGL: createLayer }, maplibre] = await Promise.all([
        import("@maplibre/maplibre-gl-leaflet"),
        import("maplibre-gl"),
      ]);
      ensureRTLTextPlugin(maplibre.setRTLTextPlugin);
      vectorLayer = await createVectorLayer(
        createLayer,
        leaflet,
        map,
        darkMode,
        token
      );
    } catch {
      // No chunk, no vector map - but still a map.
    }
    if (vectorLayer) {
      return vectorLayer;
    }
  }
  return createRasterLayer(leaflet, map, token);
};
