// The colors the map is drawn in out of the box: the VersaTiles "colorful"
// cartography repainted to the Open Home Foundation vector map concept, with
// the road hierarchy and the land-use tints worked out against it.
//
// build-scripts/gulp/map-assets.js imports this too, and Node loads it as it
// is: keep the module free of runtime imports, and of TypeScript that is not
// simply erased.

/** Drawn on the light palette */
export const HA_MAP_COLORS = {
  background: "#f4efe6",
  land: "#f4efe6",
  water: "#bcd9e8",
  labelWater: "#5b86a3",
  natureWood: "#cfe1bf",
  natureGrass: "#e2ecda",
  naturePark: "#cfe1bf",
  natureLeisure: "#e2ecda",
  natureAgriculture: "#e8eee2",
  natureWetland: "#e5ebe0",
  natureSand: "#f1eadf",
  natureRock: "#f1eadf",
  glacier: "#f9f6f1",
  areaResidential: "#efe8dc",
  areaCommercial: "#f4e1db",
  areaIndustrial: "#ede5ce",
  areaWaste: "#ece3d5",
  areaBurial: "#efe8dc",
  siteParking: "#ede6d8",
  siteSports: "#cfe1bf",
  building: "#e7ddca",
  buildingBg: "#dcccb2",
  roadStreet: "#fcfaf8",
  roadStreetBg: "#e6dac7",
  roadTrunk: "#fbe6c2",
  roadTrunkBg: "#e5cea5",
  roadMotorway: "#ebd4ab",
  roadMotorwayBg: "#deba78",
  transitRail: "#e9dfce",
  transitSubway: "#eae1d1",
  transitCycle: "#f2ede3",
  transitFoot: "#f2ede3",
  boundary: "#d6c3a4",
  boundaryDisputed: "#e2d6c0",
  label: "#4a463d",
  labelHalo: "#faf8f5",
  labelSymbol: "#8d8676",
  labelPoi: "#8d8676",
  labelShield: "#faf8f4",
  labelHousenumber: "#8d8676",
};

/** Drawn on the dark palette, in full: a light value left standing here would
 * show through on a dark map. */
export const HA_MAP_COLORS_DARK = {
  background: "#191b2c",
  land: "#191b2c",
  water: "#27357a",
  labelWater: "#9cc0f0",
  natureWood: "#254948",
  natureGrass: "#213b39",
  naturePark: "#28504b",
  natureLeisure: "#213532",
  natureAgriculture: "#203233",
  natureWetland: "#253337",
  natureSand: "#2a2c3d",
  natureRock: "#2a2c3d",
  glacier: "#2a2c3d",
  areaResidential: "#1d2034",
  areaCommercial: "#29213a",
  areaIndustrial: "#242431",
  areaWaste: "#1d2034",
  areaBurial: "#1d2034",
  siteParking: "#1d2034",
  siteSports: "#254139",
  building: "#21243c",
  buildingBg: "#2a2e4a",
  roadStreet: "#2b3052",
  roadStreetBg: "#1a1d33",
  roadTrunk: "#383e67",
  roadTrunkBg: "#22263f",
  roadMotorway: "#454d7d",
  roadMotorwayBg: "#2a2f4c",
  transitRail: "#2c3150",
  transitSubway: "#2c3150",
  transitCycle: "#2b3052",
  transitFoot: "#2b3052",
  boundary: "#3b4068",
  boundaryDisputed: "#3b4068",
  label: "#e7ecf8",
  labelHalo: "#12141f",
  labelSymbol: "#959dbd",
  labelPoi: "#959dbd",
  labelShield: "#191b2c",
  labelHousenumber: "#959dbd",
};
