// https://community.home-assistant.io/t/slate-a-new-dark-theme/86410
export const demoThemeKernehed = () => ({
  "text-primary-color": "var(--primary-text-color)",
  "primary-color": "#2980b9",
  "label-badge-red": "var(--accent-color)",
  "primary-text-color": "#FFFFFF",
  "light-primary-color": "var(--accent-color)",
  "primary-background-color": "#222222",
  "sidebar-icon-color": "#777777",
  "secondary-background-color": "#222222",
  "disabled-text-color": "#777777",
  "paper-grey-200": "#222222",
  "label-badge-background-color": "#222222",
  "table-row-background-color": "#292929",
  "paper-grey-50": "var(--primary-text-color)",
  "switch-checked-color": "var(--accent-color)",
  "secondary-text-color": "#b58e31",
  "error-color": "#b58e31",
  "divider-color": "rgba(0, 0, 0, .12)",
  "success-color": "#2980b9",
  "switch-unchecked-button-color": "var(--disabled-text-color)",
  "label-badge-border-color": "green",
  "card-background-color": "#292929",
  "label-badge-text-color": "var(--primary-text-color)",
  "switch-unchecked-track-color": "var(--disabled-text-color)",
  "dark-primary-color": "var(--accent-color)",
  "accent-color": "#2980b9",
  "table-row-alternative-background-color": "#292929",
});
