// https://community.home-assistant.io/t/slate-a-new-dark-theme/86410
export const demoThemeKernehed = () => ({
  "text-primary-color": "var(--primary-text-color)",
  "paper-item-icon-color": "var(--primary-text-color)",
  "primary-color": "#2980b9",
  "label-badge-red": "var(--accent-color)",
  "paper-tabs-selection-bar-color": "green",
  "paper-slider-knob-color": "var(--accent-color)",
  "primary-text-color": "#FFFFFF",
  "light-primary-color": "var(--accent-color)",
  "primary-background-color": "#222222",
  "sidebar-icon-color": "#777777",
  "paper-item-selected_-_background-color": "#292929",
  "paper-slider-active-color": "var(--accent-color)",
  "secondary-background-color": "#222222",
  "paper-slider-container-color":
    "linear-gradient(var(--primary-background-color), var(--secondary-background-color)) no-repeat",
  "paper-slider-disabled-active-color": "var(--disabled-text-color)",
  "disabled-text-color": "#777777",
  "paper-item-icon_-_color": "green",
  "paper-grey-200": "#222222",
  "label-badge-background-color": "#222222",
  "paper-card-header-color": "var(--accent-color)",
  "paper-listbox-background-color": "#141414",
  "table-row-background-color": "#292929",
  "paper-grey-50": "var(--primary-text-color)",
  "switch-checked-color": "var(--accent-color)",
  "paper-dialog-background-color": "#292929",
  "secondary-text-color": "#b58e31",
  "google-red-500": "#b58e31",
  "divider-color": "rgba(0, 0, 0, .12)",
  "google-green-500": "#2980b9",
  "switch-unchecked-button-color": "var(--disabled-text-color)",
  "label-badge-border-color": "green",
  "paper-listbox-color": "#777777",
  "paper-slider-disabled-secondary-color": "var(--disabled-text-color)",
  "paper-card-background-color": "#292929",
  "label-badge-text-color": "var(--primary-text-color)",
  "paper-slider-knob-start-color": "var(--accent-color)",
  "switch-unchecked-track-color": "var(--disabled-text-color)",
  "dark-primary-color": "var(--accent-color)",
  "paper-slider-secondary-color": "var(--secondary-background-color)",
  "paper-slider-pin-color": "var(--accent-color)",
  "paper-item-icon-active-color": "#b58e31",
  "accent-color": "#2980b9",
  "table-row-alternative-background-color": "#292929",
});
