#!/bin/sh
# Build the demo

# Stop on errors
set -e

cd "$(dirname "$0")/.."

OUTPUT_DIR=dist

rm -rf $OUTPUT_DIR

cd ..
DEMO=1 ./node_modules/.bin/gulp build-translations gen-icons
cd demo

NODE_ENV=production ../node_modules/.bin/webpack -p --config webpack.config.js
