name: Release Drafter

on:
  push:
    branches:
      - dev

permissions:
  contents: read

jobs:
  update_release_draft:
    permissions:
      # write permission for contents is required to create a github release
      contents: write
      # write permission for pull-requests is required for autolabeler
      # otherwise, read permission is required at least
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@b1476f6e6eb133afa41ed8589daba6dc69b4d3f5 # v6.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
