name: Stale

# yamllint disable-line rule:truthy
on:
  schedule:
    - cron: "0 * * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - name: 90 days stale policy
        uses: actions/stale@v3.0.13
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-stale: 90
          days-before-close: 7
          operations-per-run: 25
          remove-stale-when-updated: true
          stale-issue-label: "stale"
          exempt-issue-labels: "no-stale,Help%20wanted,help-wanted,feature-request,feature%20request"
          stale-issue-message: >
            There hasn't been any activity on this issue recently. Due to the
            high number of incoming GitHub notifications, we have to clean some
            of the old issues, as many of them have already been resolved with
            the latest updates.

            Please make sure to update to the latest Home Assistant version and
            check if that solves the issue. Let us know if that works for you by
            adding a comment 👍

            This issue has now been marked as stale and will be closed if no
            further activity occurs. Thank you for your contributions.

          stale-pr-label: "stale"
          exempt-pr-labels: "no-stale"
          stale-pr-message: >
            There hasn't been any activity on this pull request recently. This
            pull request has been automatically marked as stale because of that
            and will be closed if no further activity occurs within 7 days.

            Thank you for your contributions.
